server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.30.1.54:3306/tae?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: tae
    password: admin

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  logging:
    file:
      path: /logs/dev
      pattern:
        dateformat: yyyy-MM-dd HH:mm:ss
    level:
      root:
        level: warn
        additivity: false
      com:
        toy:
          pro:
            post:
              service:
                PostService:
                  level: info
                  additivity: false

            global:
              exception:
                GlobalExceptionHandler:
                  level: error
                  additivity: false
